from pathlib import Path

BASE_DIR = Path.cwd()
LOGO_DIR = BASE_DIR / 'data' / 'logo.ico'
PARQUET_PATH = BASE_DIR / 'data' / "space_missions.parquet"
CSV_DIR = BASE_DIR / 'data' / 'space_missions.csv'


PRIMARY_COLOR   = "#0F90DB" 
SECONDARY_COLOR = "#1565C0"  
TERTIARY_COLOR  = "#1E88E5" 
QUATERNARY_COLOR = "#42A5F5"
QUINARY_COLOR   = "#90CAF9" 
SENARY_COLOR    = "#E3F2FD"

SCALE_COLOR_MAP = 'Blues'

CATEGORIES_COLORS = [
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    TERTIARY_COLOR,
    QUATERNARY_COLOR,
    QUINARY_COLOR,
    SENARY_COLOR
]