[theme]
primaryColor = "#4A148C"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
[server]
folderWatchBlacklist = ["venv", ".venv", "data", "__pycache__"]